spring:
  application:
    name: charge-detail-service

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/V1__init.sql

  datasource:
    url: jdbc:h2:file:~/h2/charge-detail-service
    username: sa
    password: ''
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  servlet:
    context-path: /api/v1/